#spring:
#  data:
#    mongodb:
#      uri: mongodb://localhost:27017/focusclock
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    password: jyx2000124
#    url: jdbc:mysql://localhost:3306/focusclock?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT&allowPublicKeyRetrieval=true
#    username: root
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8
#  jpa:
#    hibernate:
#      ddl-auto: update
#    open-in-view: true
#    show-sql: true
#  main:
#    allow-bean-definition-overriding: true
#server:
#  port: 8181
server:
  port: 8080
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/focusclock?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true
#  main:
#    allow-bean-definition-overriding: true